name: ShowServerDate_Action
on:
  schedule:  
  - cron: '*/5,*,*,*,*'
  
jobs:
  myJob:
  runs-on: ubuntu-latest
  steps :
    - name: show current date
      run: echo "current server date is ($date)"

