name: Print Test Sentence (workflow)
on:
  push:
    branches:
      - dev

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Print Test Sentence
        run: echo "I am a test workflow"
