name: This is a sample workflow 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: check-out my repo
       uses: actions/checkout@v2
     - name: setup Phyton
       uses: actions/setup-python
     - name: push my repo
git config reza.mesgaran Github-actions
git add .
git commit -m "my new commit"
git push
    
